name: Trigger DevOps Workflow

on:
  push:
    branches:
      - develop

jobs:
  call-devops-workflow:
    uses: aaishashaik/devops-workflows/.github/workflows/hello-world.yml@main
    with:
      environment: dev
